#数据源
data-source:
  dataUserName: root
  dataPasswd: root
  dataUrl: jdbc:mysql://127.0.0.1:3306/liuguangjie?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

debug: false

spring:
  profiles:
    active: dev

logging:
  level.root: info
  path: logs/
  file: myProject.log



---
spring:
  profiles: dev
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
    pool:
      max-active: 8

